name: fixgo_components
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  flutter_bloc: ^9.1.1
  google_sign_in: ^5.4.2
  cloud_firestore: ^6.0.3
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  table_calendar: ^3.0.9
  intl: ^0.19.0
  flutter_form_builder: ^9.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geocoding: ^3.0.0
  fl_chart: ^0.66.2
  pdf: ^3.11.0
  printing: ^5.13.4
  path_provider: ^2.1.3

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
